### ISSUE TITLE
'generator' object is not subscriptable

### ISSUE THREAD

**Issue by wjmb** [Kirgnition/raspy-temperature-bot#1] opened 2021-12-08 10:15 UTC
Hi, in the log-file I get some TypeErrors, for example:

```
File "/home/wjmb/raspy-temperature-bot/graph.py", line 50, in make_graph
    datemin = dates[0]
TypeError: 'generator' object is not subscriptable
```

or:

```
File "/home/wjmb/raspy-temperature-bot/bot.py", line 53, in last_readings
    timestr = data.dates[0].datetime.strftime('%Y/%m/%d at %H:%M')
TypeError: 'generator' object is not subscriptable
```

This is on a RPI4, Python version 3.9.2

**Comment by KirkBuah** [comment] 2021-12-08 19:23
Hi, i looked into it and i should have fixed it. I currently don't have the setup to test it so let me know if it works.

**Comment by wjmb** [comment] 2021-12-08 19:26
Thanks ... allow me a few days ... will get back to you.

**Comment by wjmb** [comment] 2021-12-09 10:28
Hi,

It doesn't work yet. I still get  

`  File "/home/wjmb/raspy-temperature-bot/bot.py", line 53, in last_readings
    timestr = data.dates[0].datetime.strftime('%Y/%m/%d at %H:%M')
TypeError: 'generator' object is not subscriptable
`

And a new one:

`  File "/home/wjmb/raspy-temperature-bot/bot.py", line 40, in temperature_graph
    Graph(hours).make_graph()
  File "/home/wjmb/raspy-temperature-bot/graph.py", line 50, in make_graph
    datemin = dates[0]
IndexError: list index out of range
`

**Comment by KirkBuah** [comment] 2021-12-09 10:45
If you can give me a day or two to recreate the setup i'll solve that, thanks for your patience :)

**Comment by wjmb** [comment] 2021-12-09 10:49
No hurry ... thanks for looking into this. Hope you can reproduce and fix it .. This is my first exposure to Python, so a bit over my head still.

**Comment by wjmb** [comment] 2022-01-04 22:11
Did you have a chance to look into this?

**Comment by KirkBuah** [comment] 2022-01-04 22:19
Hi! I want to be honest with you, i looked it up and i honestly can't
figure out why it isn't working. I had a previous version that didn't rely
on a database but on a simple .txt file, I can look for that in my hard
drive right now and report back to you in a few minutes.

Il mar 4 gen 2022, 23:12 Wouter ***@***.***> ha scritto:

**Comment by wjmb** [comment] 2022-01-04 22:25
Were you able to reproduce, or is this just happening on my rpi?

**Comment by KirkBuah** [comment] 2022-01-04 22:29
Yes i was able to reproduce it but i was unable to find the cause. I found the old version by the way, i'm tweaking a few things right now and i'll upload it in another branch.

**Comment by wjmb** [comment] 2022-01-04 22:31
Thanks for looking into this. Sorry that the cause couldn't be found. I will try the other branch once you uploaded it. Thanks again.

**Comment by KirkBuah** [comment] 2022-01-04 22:32
I'm the one to be sorry about it, it was my first time using a sqlite database so it's very possible i might have messed up something. i'll let you know as soon as i upload it.

**Comment by KirkBuah** [comment] 2022-01-04 23:08
The other branch is online, let me know if you run into other bugs.

**Comment by KirkBuah** [comment] 2022-01-04 23:09
Also, the installation procedure is pretty much the same, but let me know if you get stuck anywhere.

**Comment by wjmb** [comment] 2022-01-06 22:36
Yes ... I made some progress, but now I am stuck on ./obj/temperature.json. If the file does not exist, it complains. If I touch the file it gets confused about the lack of content. Can you give me an example of the content of the file? Sorry for being such a Python noob.

**Comment by KirkBuah** [comment] 2022-01-06 23:21
Don't worry! Could you clarify which is the file that gives you that error? Is it sensor.py , bot.py or another one?

**Comment by wjmb** [comment] 2022-01-06 23:24
```
Traceback (most recent call last):
  File "/home/wjmb/test/raspy-temperature-bot/bot.py", line 15, in <module>
    import sensor
  File "/home/wjmb/test/raspy-temperature-bot/sensor.py", line 54, in <module>
    write()
  File "/home/wjmb/test/raspy-temperature-bot/sensor.py", line 48, in write
    save_obj(tempdict)
  File "/home/wjmb/test/raspy-temperature-bot/sensor.py", line 16, in save_obj
    dic = json.load(f)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The line numbers might not completely match anymore ... This is with ./obj/temperature.json file present, but empty

**Comment by KirkBuah** [comment] 2022-01-06 23:29
try paste this into your json file:
`{"2020/10/19 - 17:21:48": [20.5, 68.5999984741211, [20, 0.5]]}`

**Comment by wjmb** [comment] 2022-01-06 23:39
Thanks, that worked. From here on I should manage :-)

**Comment by KirkBuah** [comment] 2022-01-06 23:46
Ok let me know if you find any other problems! I'll close this issue.
Also sorry for the troublesome installation process, this was my first big project which i've completed 2 years ago, so it's not perfect and i'm a bit rusty too :) Thanks for your patience!

**Closed as completed** 2022-01-07 09:10 UTC
